<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NuBlox.Persistence.Postgres</AssemblyName>
    <RootNamespace>NuBlox.Persistence.Postgres</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../NuBlox.Kernel/NuBlox.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
