<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>NuBlox.Observability.Tests</AssemblyName>
    <RootNamespace>NuBlox.Observability.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NuBlox.Observability/NuBlox.Observability.csproj" />
  </ItemGroup>
</Project>
